### ISSUE TITLE
0 results found in 0ms

### ISSUE THREAD

**Issue by FullStackTiger** [typesense/gatsby-plugin-typesense#4]
## Description

I am getting `0 results found in 0ms`.
details: 
```{facet_counts: [], found: 0, hits: [], page: 1, request_params: {per_page: 10, q: "about"},…}
facet_counts: []
found: 0
hits: []
page: 1
request_params: {per_page: 10, q: "about"}
search_time_ms: 0
```

I am using **Typesense Cloud** as a server, and using this plugin on the gatsby project, follows this [tutorial](https://www.gatsbyjs.com/plugins/gatsby-plugin-typesense/?=typesen#gatsby-plugin-typesense-npm-version-circleci)
This is not a simple test project, we are using Algolia, but I would like to use Typesense.
Correctly how to fix this issue?

## Steps to reproduce

I added this code each pages:
```
      <h1 data-typesense-field="title">About Us</h1>
      <p data-typesense-field="description">test test description</p>
      <span data-typesense-field="tags">about</span>
```

**When gatsby build, I getting these warnning**: 
```
No HTMLelements had the data-typesense-field attribute, skipping page
No HTMLelements had the data-typesense-field attribute, skipping page
No HTMLelements had the data-typesense-field attribute, skipping page
No HTMLelements had the data-typesense-field attribute, skipping page
...
```

## Expected Behavior

it seems this plugin doesn't index each page 

## Actual Behavior

Correctly, how to check the index each page in dev environment?

## Metadata

**Typsense Version**: Typesense v0.17.0

**OS**: Typesense Cloud

**Comment by jasonbosco** [comment]
@FullStackTiger That warning message seems strange. What this plugin essentially does, is it scans the `public` directory post build for any HTML files and looks for elements with the `data-typesense-field` attribute. 

When you run `gatsby build`, may I know the structure of your `public` directory that gets generated? If you're able to zip the whole public dir and share it with me (jason at typesense d0t org), that would help a lot. 

Btw, here's an example of a minimal Gatsby application that shows the plugin in action along with react-instantsearch: https://github.com/typesense/gatsby-plugin-typesense/tree/83adc28ff315f5a52800ef0658515799df8d6146/test/support/testground

**Comment by jasonbosco** [comment]
Closing this for now, feel free to re-open with more info.
