### ISSUE TITLE
Customizing extract directories?

### ISSUE THREAD

**Issue by artt** [typesense/gatsby-plugin-typesense#8]
Refer to #6

Since some people might need to create a collection in paths other than `publicDir`, I'd like to propose changing this to something like `collectionRoot` (of course, also make it backward compat) and adding an option `excludeDir` to take in regular expression so that the "crawler" can skip undesired paths.

Please lmk if you think this would be useful and I can submit a PR.

**Comment by jasonbosco** [comment]
Ah right. That sounds useful to me. A PR would be great 🙏

**Comment by jasonbosco** [comment]
Just published this in `v0.3.0`
